---
name: ci

"on":
  pull_request:
  push:
    branches:
      - main

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Run yaml Lint
        uses: actionshub/yamllint@main

  mdl:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Run Markdown Lint
        uses: actionshub/markdownlint@main

  terraform-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Lint Terraform
        uses: actionshub/terraform-lint@main
